### ISSUE TITLE
Connect fails after update from 1.0.1 to 1.0.3

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript#458]
> We are only using the ObjectScript Extension – nothing else.
> 
> Our connection setup works on 1.0.1  … what happened with 1.0.3 … it does not work?
> 
> I can simply switch out the extension versions, back and forth, in VS code with no changes to our Cache setups or settings.json file.
> 
> Version 1.0.1 works
> Version 1.0.3 does not.
> 
> What can I say?  No Changes in our Cache configuration or Settings.Json files.
> 
> Our setup is simple:
> 
>  "objectscript.conn": {
> 
>       "active": true,
>       "label": "mltestsrv1",
>       "host": "mltestsrv1",
>       "port": 57772,
>       "username": "PXS",
>       "password": "",
>       "ns": "PXS",
>       "https": false,
>     },
> 
> So something does not seem correct on the extension.
> 
> For now, we have to stay on 1.0.1 or our developers are dead in the water.

_Originally posted by @PaulSiml in https://github.com/intersystems-community/vscode-objectscript/issues/454#issuecomment-719720154_

**Comment by gjsjohnmurray** [comment]
@PaulSiml please download https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.5-beta.2/vscode-objectscript-1.0.5-beta.2.vsix and install that. One way is to drag and drop it onto the extensions list in VS Code.

Then let us know if the problem is resolved.

**Comment by gjsjohnmurray** [comment]
@PaulSiml are you able to verify the fix in the beta (see previous link)? It would be good to have confirmation from you before we publish it in the next version.

**Comment by gjsjohnmurray** [comment]
https://github.com/intersystems-community/vscode-objectscript/issues/454#issuecomment-720473610 confirms fixed. Will ship in 1.0.5.

**Comment by PaulSiml** [comment]
I verified that this had been fixed in 1.0.5-beta.  However, this morning I loaded 1.0.5 and I am no longer prompted for a password and therefore cannot connect to a namespace.  Did this fix make it into 1.0.5?  Dropping back to 1.0.5-beta.

**Comment by gjsjohnmurray** [comment]
@PaulSiml which exact beta are you using which does what you expect, in contrast to the 1.0.5 release? AFAIK no changes that were part of a beta were subsequently removed, but it's possible that another change between the beta you tried and the point at which we released 1.0.5 could have affected your scenario.

**Comment by PaulSiml** [comment]
The problem was resolved in the beta version.

As per your instructions, I am using:

@PaulSiml<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPaulSiml&data=04%7C01%7Cpaul.siml%40conduent.com%7Cfe8697d8b8ef4f64214d08d87d28d769%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637396961651118626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9WFafVTFClGX7%2FB8G0EuEiijvDGkUMfTAMlej5WP798%3D&reserved=0> please download https://github.com/intersystems-community/vscode-objectscript/releases/download/v1.0.5-beta.2/vscode-objectscript-1.0.5-beta.2.vsix<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fintersystems-community%2Fvscode-objectscript%2Freleases%2Fdownload%2Fv1.0.5-beta.2%2Fvscode-objectscript-1.0.5-beta.2.vsix&data=04%7C01%7Cpaul.siml%40conduent.com%7Cfe8697d8b8ef4f64214d08d87d28d769%7C1aed4588b8ce43a8a775989538fd30d8%7C0%7C0%7C637396961651118626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BTAtBNFilIHdN%2FlojuCdxQ0c%2BceMVzX3sqxiwaS5sBI%3D&reserved=0> and install that. One way is to drag and drop it onto the extensions list in VS Code.

**Comment by gjsjohnmurray** [comment]
@PaulSiml so you have a problem with 1.0.5 which you don't have with 1.0.5-beta.2

There were ten betas before 1.0.5. Please go to https://github.com/intersystems-community/vscode-objectscript/releases?after=v1.0.5 and try to discover which one after beta.2 first causes the problem.

One way to do this is to bisect, i.e. try beta.6 first. If this fails try beta.4 next, or if beta.6 works try beta.8 next.

**Comment by PaulSiml** [comment]
Ok … I will let you know.

**Comment by PaulSiml** [comment]
1.0.5-beta.7 works …. 1.0.5-beta.8 fails

So the problem is back in beta.8 with a slight variation … we don’t receive the password prompt at all.  In the previous failure we were presented the prompt but it would not accept the input.

**Comment by gjsjohnmurray** [comment]
Fixed in 1.0.6-beta.6
