### ISSUE TITLE
Error with VSCode Insider Edition

### ISSUE THREAD

**Issue by RyszardWithAZ** [intersystems-community/vscode-objectscript#791]
This MAY be a bug with the new VSCode Insider Edition (see bottom for version info), but I still wanted to give you a heads-up in case it's an issue with the plug-in too.

With the existing release of VSCode, it works, but with the VSCode Insider Edition, I can't connect to IRIS, I get these errors:

![image](https://user-images.githubusercontent.com/63731219/144098808-9030c81d-7b9b-486c-9fec-1e1b2877418c.png)

and 

![image](https://user-images.githubusercontent.com/63731219/144098833-0f7a959b-f746-4f27-87f4-4476fa7e7356.png)

VSCode Insider Edition version info:

Version: 1.63.0-insider (user setup)
Commit: 827f76521d33a61c19e92160649a0a6af8bad132
Date: 2021-11-30T11:58:52.241Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by isc-bsaviano** [comment]
@daimor Can you look into this? beta.9 contains your web extension commits

**Comment by isc-bsaviano** [comment]
@RyszardWithAZ I installed 1.1.2-beta.9 in regular VS Code and Insiders on my Mac and was able to reproduce this error on both. Is this the same for you?

**Comment by daimor** [comment]
There a bit more, than just only web extension support, I've also removed some of seems unused modules as well
I'll have a look

**Comment by daimor** [comment]
the issue in updated node-fetch, https://github.com/node-fetch/node-fetch/issues/1367
returned version back to working version with PR

**Comment by RyszardWithAZ** [comment]
> @RyszardWithAZ I installed 1.1.2-beta.9 in regular VS Code and Insiders on my Mac and was able to reproduce this error on both. Is this the same for you?

I also upgraded to beta.9 BUT I also downgraded back to beta.5 and still had the error in VSCode Insider. I didn't want to play with my regular VSCode because I need SOME connection working.

**Comment by RyszardWithAZ** [comment]
> Could you check this version? https://github.com/intersystems-community/vscode-objectscript/suites/4510548122/artifacts/120500832

I installed it in VSCode Insider and still the same issue.

**Comment by daimor** [comment]
Did you reload?
Did Output got this?
```
intersystems-community.vscode-objectscript version 1.1.2-dev.792 activating with proposed APIs available.
```
with exactly this version number

**Comment by daimor** [comment]
I made one more build with a change, which should have any differences.
https://github.com/intersystems-community/vscode-objectscript/suites/4511335169/artifacts/120533447
I tried the previous build, and it worked well

**Comment by RyszardWithAZ** [comment]
> Did you reload? Did Output got this?
> 
> ```
> intersystems-community.vscode-objectscript version 1.1.2-dev.792 activating with proposed APIs available.
> ```
> 
> with exactly this version number

Yes I reloaded, and in fact I tried reloading VSCode multiple times, but no, I never get that output in the Insiders Edition. I wonder if this is the same issue when I tried downgrading it to beta.5 with no luck.

I felt brave and applied your new build to my regular VSCode and it did indeed work and I get that output. So my regular VSCode is fine with this new build.

So, my Insiders Build is broken, I can't seem to downgrade it either.  I also tried totally deleting the ObjectScript (and Language Server) extensions and reinstall them from scratch, that also didn't work!

**Comment by daimor** [comment]
> So, my Insiders Build is broken, I can't seem to downgrade it either. I also tried totally deleting the ObjectScript (and Language Server) extensions and reinstall them from scratch, that also didn't work!
It does not work with the same issue with node:http?
Command Developer: Show Running Extensions, should show this version
![image](https://user-images.githubusercontent.com/1212251/144190362-7e0eca8e-6549-4ee3-8086-0d99bf78c538.png)

If it does not work. Probably, you'd need to reinstall VSCode Insiders.

**Comment by isc-bsaviano** [comment]
@daimor I installed the `dev.792` vsix in my regaulr VS Code and it works now. However, it's still not working on Insiders. I updated Insiders this morning, installed `dev.792` and opened a `.code-workspace` that contains 2 `isfs` folders. The main extension didn't activate and nothing was written to the `ObjectScript` Output channel.

**Comment by daimor** [comment]
So, it looks like it was not even activated. Any other logs from VSCode?

**Comment by isc-bsaviano** [comment]
@daimor I found this in the Window Log:

> [2021-12-01 09:03:36.707] [renderer3] [critical] Extension 'intersystems-community.vscode-objectscript CANNOT USE these API proposals 'fileSearchProvider, textSearchProvider'. You MUST start in extension development mode or use the --enable-proposed-api command line flag

And this in the Extension Host Log:

> [2021-12-01 09:03:40.455] [exthost] [error] Activating extension intersystems-community.vscode-objectscript failed due to an error:
[2021-12-01 09:03:40.455] [exthost] [error] Error: Extension 'intersystems-community.vscode-objectscript' CANNOT use API proposal: fileSearchProvider.
Its package.json#enabledApiProposals-property declares:  but NOT fileSearchProvider.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api intersystems-community.vscode-objectscript
	at w (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:80837)
	at Object.registerFileSearchProvider (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:37507)
	at t.activate (/Users/bsaviano/.vscode-insiders/extensions/intersystems-community.vscode-objectscript-1.1.2-dev.792/dist/extension.js:1:441960)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async Promise.all (index 0)

**Comment by isc-bsaviano** [comment]
After adding this line to my Insiders' argv.json, everything works:

```json
"enable-proposed-api": ["intersystems-community.vscode-objectscript"]
```

Previously this was only required for regular VS Code but I guess it's required for Insiders as well now

**Comment by daimor** [comment]
Well, here it is. So, it's another issue, could you make it separate. And we will finish this issue, which I think you agree is solved. And I'll see to this issue with proposed api

**Comment by isc-bsaviano** [comment]
@daimor Done. I think we can merge your PR and close this issue

**Comment by RyszardWithAZ** [comment]
Thank you, I also added that to my argv.json and Insiders also now works. Thanks again, especially for the very fast attention!

**Comment by Taulim** [comment]
Seems that node-fetch was upgraded again on the PR #840 and this issue is back.  

I downgraded to the previous beta (1.4.2-beta.3) to make it work.

**Comment by gjsjohnmurray** [comment]
@Taulim thanks for the alert. The issue is now fixed in 1.4.2-beta.5
